Fixed path

diff --git a/.github/workflows/autorebuild.yml b/.github/workflows/autorebuild.yml
--- a/.github/workflows/autorebuild.yml
+++ b/.github/workflows/autorebuild.yml
@@ -38,6 +38,7 @@ jobs:
         working-directory: ./source/c/build
         shell: bash
         run: |
+          set -eux
           EDIR=$(ls | grep -E '^hdf5-([0-9.]+)$')
           if [[ ! -d "${EDIR}" ]]; then
             echo "::error title=Cannot find build directory ::Cannot find build directory (detected ${EDIR}) for HDF5 version out of $(ls)"
@@ -54,15 +55,15 @@ jobs:
             echo "::warning title=Cannot find workflow subdirectory ::Cannot find directory ${OLD_PDIR}, changed to ${PDIR}"
           fi
           if [[ ! -d "${PDIR}" ]]; then
-            echo "::warning title=Directory heuristic failed :: Still cannot find workflow build directory ${PDIR}"
+            echo "::error title=Directory heuristic failed :: Still cannot find workflow build directory ${PDIR}"
           fi
-          tar -c "${PDIR}" | zstd -z --adapt -T0 -v -o ./hdf5_package.tar.zst
+          tar -C "${PDIR}" -c . | zstd -z --adapt -T0 -v -o ./hdf5_package.tar.zst
 
       - name: 'Artifact upload: HDF5 built package (Linux)'
         uses: actions/upload-artifact@v4
         with:
           name: hdf5_linux_package
-          path: './source/c/hdf5_package.tar.zst'
+          path: './source/c/build/hdf5_package.tar.zst'
           compression-level: 0
           if-no-files-found: error
 
